services:
  redis:
    image: redis:7-alpine
    container_name: pos-redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: pos-api
    command: npm run dev
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis

  worker:
    build: .
    container_name: pos-worker
    command: npm run worker
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis